id = "zx"
name = "ZX"
description = "ZX support."
version = "0.1.0-dev.323"
schema_version = 1
authors = ["Nurul Huda (Apon) <me@nurulhudaapon.com>"]
repository = "https://github.com/nurulhudaapon/zx"

[language_servers.zls]
name = "zls"
language = "ZX"

[grammars.zx]
repository = "https://github.com/nurulhudaapon/zx"
path = "tree-sitter-zx"
rev = "main"

[debug_locators.zx-locator]
