id = "zx"
name = "ZX"
description = "Zig and ZX support."
version = "0.0.1"
schema_version = 1
authors = ["Nurul Huda (Apon) <me@nurulhudaapon.com>"]
repository = "https://github.com/nurulhudaapon/zx"

[language_servers.zls]
name = "zls"
language = "Zig"

[grammars.zig]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-zig"
commit = "6479aa13f32f701c383083d8b28360ebd682fb7d"

[debug_locators.zig-locator]
